# Generated by Django 3.2.5 on 2021-10-09 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0002_auto_20211009_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kakeibo',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kakeibo.category', verbose_name='カテゴリ'),
        ),
    ]
